# Generated by Django 6.0.3 on 2026-04-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='korildi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='nashr_etilgan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='yangilangan_sana',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
