# Generated by Django 6.0.3 on 2026-04-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_korildi_post_nashr_etilgan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kategoriya',
            field=models.CharField(choices=[('texnologiya', 'Texnologiya'), ('hayot', 'Hayot'), ('sport', 'Sport')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('matn', models.TextField()),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
