# Generated by Django 6.0.3 on 2026-04-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_kategoriya_izoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='postlar/'),
        ),
    ]
