# Generated by Django 6.0.3 on 2026-04-07 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_yaratilgan_izoh_yaratilgan_sana_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(default='profillar/default.jpg', upload_to='profillar/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('tugilgan_sana', models.DateField(blank=True, null=True)),
                ('manzil', models.CharField(blank=True, max_length=200)),
                ('foydalanuvchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
