# Generated by Django 6.0.3 on 2026-04-08 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-yaratilgan_sana']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='kategoriya',
        ),
        migrations.AlterField(
            model_name='post',
            name='sarlavha',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='yaratilgan_sana',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-yaratilgan_sana', 'nashr_etilgan'], name='blog_post_yaratil_7b945e_idx'),
        ),
    ]
